### ISSUE TITLE
Displaying input validation (success or failure) in EventNXT login page

### ISSUE THREAD

**Issue by Rohith-Yogi** [CSCE-606-Event360/EventNXT#1]
As a User, when I click on login button
I want to see the validation results
So that I can check status (successful/failure) of login

**Comment by pkavu-1998-tamu** [comment]
Developed feature to Authorize and validate the login by considering response codes.
This Feature is developed in Old EventNxT App.

Heroku Link for the same: https://eventnxtprodfall2023-a37dec4f8dd9.herokuapp.com/
Git hub repo : https://github.com/CSCE-606-Event360/EventNXT/tree/main/EventNXT_old_app

Snippet for the same is as follows:

![Image](https://github.com/CSCE-606-Event360/EventNXT/assets/143028516/efc348c2-09ee-4123-a87d-9343b8632916)
