### ISSUE TITLE
Test the work flow of user login from Events360 to EventNxt

### ISSUE THREAD

**Issue by rakesh-pothineni** [CSCE-606-Event360/EventNXT#29]

**Comment by skybluego123** [comment]
.

**Comment by pkavu-1998-tamu** [comment]
In this user story, we have first registered our test_app with events360 CRM and then we have used the client id and client secret given by CRM in our client test_app as environment variables. Created necessary routes to do authorization token and code exchange.
Once this is done we have tested the sign in with events360 button feature and checked if user registered in events360 is signed in test_app which is eventNxt
