### ISSUE TITLE
Create routes for /auth/events360 and check with controller for response details

### ISSUE THREAD

**Issue by rakesh-pothineni** [CSCE-606-Event360/EventNXT#38]

**Comment by pkavu-1998-tamu** [comment]
Once the sign in with events 360 button is clicked, route for /oauth/authorize is called and authorize_events360 function in  authorize_request controller is called, where we redirect to authorization within events360 server with clientid, redirect_uri, etc.. details. Once the redirect request is received by events360, it tries to authorize the request by checking the session details and it returns to the given url and then signs in the user.
