### ISSUE TITLE
Product Owner Responsibilities

### ISSUE THREAD

**Issue by anirith-tamu** [CSCE-606-Event360/EventNXT#84]

**Comment by rakesh-pothineni** [comment]
As a Product Owner, my responsibilities include defining and prioritizing the product backlog, collaborating with stakeholders to gather and prioritize requirements, and ensuring that the development team's work aligns with the overall product vision and goals. I am responsible for conveying clear user stories, acceptance criteria, and feature priorities to the development team. Additionally, I engage in continuous communication with stakeholders to gather feedback and adjust priorities as needed.
