### ISSUE TITLE
Deploy and test EventNXT integration with Events360 (CRM) in production environment

### ISSUE THREAD

**Issue by pkavu-1998-tamu** [CSCE-606-Event360/EventNXT#85]
We have tested the CRM integration with EventNXT in development environment using a module provided by devise called developer. Now as part of this user story we are using custom strategy to use omniauth plugin to integrate EventNXT with Events360 and test it in heroku production environment

**Comment by rakesh-pothineni** [comment]
We have tested the CRM integration with EventNXT in a development environment using a module provided by devise called developer. Now as part of this user story we are using custom strategy to use omniauth plugin to integrate EventNXT with Events360 and test it in heroku production environment
